// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://teobcrrbxosotxjsvxvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlb2JjcnJieG9zb3R4anN2eHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMDM4NTcsImV4cCI6MjA5OTY3OTg1N30.jK_Xs5Uokj_5uqDi2bEPjLmI5katHYFjR2Y3VY0D6Ck";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);